### ISSUE TITLE
Skywars stats arent availiable

### ISSUE THREAD

**Issue by Mythbusters123** [zikeji/node-hypixel#119]
**Describe the bug**
So i was looking through the code, and it doesnt seem to document Skywars Stats well. I could be wrong on this, but it seems to only have the type of the base game, not with a different class where you can grab the data.

**To Reproduce**
Its in the api.ts file

**Expected behavior**
There should be stats just for skywars, so you can access them

**Environment:**
 - OS: [Windows 10]
 - Node Version: [12.19.0]
 - NPM Version [6.14.0]
 - Library Version [Latest]

**Comment by zikeji** [comment]
This is an enhancement request, not a bug. As I mention in the README, my API aims to be unopinionated and not change output from the API. It documents it and adds type completion for added ease of use. Some Helpers exist to fill in roles where calculations and other overhead is necessary, but in form where explicitly run the helper.

None of the objects returned by the API calls are classes - they're all the JSON results from Hypixel.

Skywars stats themselves come from two places in Hypixel's API, but all under the /player call.

Some of the SkyWars stats are available in the achievements property of the player object.

https://node-hypixel.zikeji.com/ts-api/interfaces/components.schemas.player/#achievements
https://node-hypixel.zikeji.com/ts-api/interfaces/components.schemas.playerachievements/#skywars-heads

![Code_qYGWlTmtL9](https://user-images.githubusercontent.com/9063612/102703024-a2638e00-4237-11eb-9937-889a7d44a48a.png)

The majority of the stats are in the stats property however.

https://node-hypixel.zikeji.com/ts-api/interfaces/components.schemas.player/#stats
https://node-hypixel.zikeji.com/ts-api/interfaces/components.schemas.playerstats/#skywars

![Code_TlDRKbxJkH](https://user-images.githubusercontent.com/9063612/102703042-f40c1880-4237-11eb-9d1d-5ae66eb75bda.png)

You might be referring to the typings for that property (the schema). You are correct as I haven't explored it thoroughly. However the data is there, and the possible data types will be suggested based on my exploration of Hypixel's API. Just because there aren't any suggestions doesn't mean the data isn't available - you can use `console.log` to view the properties. In this instance based on the screenshots you'd do `console.log(player.stats.SkyWars)` to view the available data for that player.

In terms of the SkyWars data it is very much like the BedWars data. In my exploration of the APIs I downloaded the player data for 6913 Hypixel players and used it to explore difference datasets.

The `player.stats.SkyWars` property has over 10 thousand unique properties - mapping that in the schema would cause alot of trouble.

You can view the mapping here: https://codebeautify.org/online-json-editor/cbffdf3a

To explain the JSON format: the "count" property shows how many existed, and properties obviously shows the properties of that object. So delving into it you can see how many instances showed up (how rare/common that data is).

![chrome_rlvTd4RU5V](https://user-images.githubusercontent.com/9063612/102703196-c922c400-4239-11eb-88eb-bf09ec96eb96.png)

So in the above example you can see the base object (stats.SkyWars) had 6853 instances out of the 6913. So SkyWars_openedChests in that screenshot shows up 4815 times. Which means a good amount of players will have the stats.SkyWars.SkyWars_openedChests property. As the data shows, that property is a "number" type.

![chrome_Esa8XxILI2](https://user-images.githubusercontent.com/9063612/102703209-0f782300-423a-11eb-8d97-7d977da0cf8f.png)

In that example you can see the activeKit_MEGA property is a string and shows up in slightly more than half of the results. That would be `stats.SkyWars.activeKit_MEGA`.

**Comment by zikeji** [comment]
@Mythbusters123 I went ahead and converted the data to a typescript definition here: https://gist.github.com/zikeji/5d63dec21fade695293355f190e0cc9e

Not sure if you're using TypeScript or just normal JS. You should be able to manually assign the stats.SkyBlock object that type in either platform.

e.g.

In typescript:
```typescript
/** interface definition here */
const player = await client.player.uuid('20934ef9488c465180a78f861586b4cf');
const skywarsStats = player.stats.SkyWars as SkyWarsStats;
```

In vanilla JS you'd need to use jsdoc - not terribly familiar but I can look into it later.

**Comment by Mythbusters123** [comment]
Wow, you didnt have to. That must have taken a ton of time. Thank you though!

**Comment by zikeji** [comment]
> Wow, you didnt have to. That must have taken a ton of time. Thank you though!

I have parsing scripts setup to pull out definitions from API data. That's how I typed out most of the interfaces - I pulled API data on a bunch of players and fed it into the script. Took a while to setup, but since it's already there I just ran it against SkyWars stats again.
